<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hsp</string>
	</array>
	<key>name</key>
	<string>HSP</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Line Comment</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.hsp</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Line Comment</string>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.hsp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>string.block.hsp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.hsp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comevdisp</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comevarg</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comevent</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>delcom</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>newcom</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>querycom</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sarraycon</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>assert</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>logmes</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>button</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>chkbox</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>clrobj</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>combox</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>input</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>listbox</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mesbox</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objenable</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objimage</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objmode</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objprm</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objsel</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objsize</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objskip</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>bcopy</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>bload</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>bsave</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>chdir</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>chdpm</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>delete</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dirlist</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exist</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>memfile</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mkdir</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>_break</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>_continue</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>case</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>default</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>for </string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>next</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>swbreak</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>swend</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>switch</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>until</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>wend</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>while</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>await</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>break</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>continue</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>else</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exec</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exgoto</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>foreach</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gosub</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>goto</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>if</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>loop</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>onclick</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>oncmd</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>onerror</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>onexit</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>onkey</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>repeat</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>return</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>run</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stop</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>wait</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mci</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mmload</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mmplay</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mmstop</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>lpeek</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>peek</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>wpeek</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>alloc</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comres</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>delmod</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ddim</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dimtype</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sdim</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ldim</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dim</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>lpoke</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>memcpy</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>memexpand</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>memset</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>newlab</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>newmod</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>poke</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>wpoke</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>axobj</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>bgscr</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>bmpsave</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>boxf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>buffer</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>celdiv</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>celload</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>celput</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>chgdisp</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>circle</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cls</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dialog</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>font</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gcopy</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gmode</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gradf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>grect</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>groll</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>grotate</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gsel</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gsquare</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gzoom</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>hsvcolor</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>line</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>palcolor</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>palette</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pget</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>picload</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pos</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>print</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pset</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>redraw</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>screen</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sendmsg</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>syscolor</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sysfont</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>title</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>width </string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>winobj</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>absf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>abs</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>atan</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>callfunc</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cos</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dirinfo</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>double</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>expf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gettime</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ginfo</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(lengt(h|h2|h3|h4))\b</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>libptr</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>limitf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>limit</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>logf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>objinfo</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>powf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>rnd</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sin</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sqrt</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>strlen</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sysinfo</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>tan</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>varptr</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>vartype</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>varuse</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getkey</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mcall</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mouse</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>randomize</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stick</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dup</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dupptr</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mref</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cnvwtos</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getpath</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>instr</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>noteinfo</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>strf</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>strmid</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>strtrim</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cnvstow</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getstr</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>noteadd</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>notedel</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>noteget</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>noteload</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>notesave</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>notesel</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>noteunsel</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>split</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>strrep</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netinit</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netterm</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netexec</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netmode</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>neterror</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>neturl</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netdlname</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netproxy</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netagent</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netheader</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netrequest</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netload</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netfileinfo</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netsize</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>filecrc</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpopen</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpclose</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>filemd5</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpresult</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpdir</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpdirlist</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpdirlist2</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpcmd</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftprmdir</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpput</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftprename</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ftpdelete</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netrequest_get</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netrequest_post</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>netgetv</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nkfcnv</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>nkfguess</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getenv</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getctime</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gfini</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gfcopy</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gfdec</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gfinc</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>hsvcolor</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>grect</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>grotate</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gsquare</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sysinfo</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sysexit</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emath</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emstr</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emcnv</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emint</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emsin</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emcos</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>emsqr</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>ematan</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>regkey</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>getreg</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>setreg</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>regkill</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>reglist</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comopen</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comclose</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>computc</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comput</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comgetc</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comstat</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>comcontrol</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxcopy</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxren</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxinfo</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxaget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxaset</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxtget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxtset</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>selfolder</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxshort</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxdir</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>fxlink</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>lzdist</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>lzcopy</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>clipset</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>clipsetg</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>clipget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplsel</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplobj</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplact</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplfocus</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplstr</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplkey</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplkeyu</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplkeyd</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>aplget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>apledit</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pipeput</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pipeget</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>pipeexec</string>
			<key>name</key>
			<string>support.function.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#addition</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#aht</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#ahtmes</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#cfunc</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#cmd</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#cmpopt</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#comfunc</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#const</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#defcfunc</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#deffunc</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#define</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#else</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#endif</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#enum</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#epack</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#func</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#global</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#if</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#ifdef</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#ifndef</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#include</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#modcfunc</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#modfunc</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#modinit</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#modterm</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#module</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#pack</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#packopt</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#regcmd</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#runtime</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#undef</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#usecom</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#uselib</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>true</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>false</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>stat</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cmdline</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>err</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dispx</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>dispy</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>winy</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>winx</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>csrx</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>csry</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>prmx</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>prmy</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>rval</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>gval</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>bval</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>paluse</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mousex</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mousey</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>exedir</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>windir</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>curdir</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>refstr</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>strsize</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>looplev</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>cnt</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>sublev</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>iparam</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>lparam</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>wparam</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>hspstat</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>hspver</string>
			<key>name</key>
			<string>constant.language.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>str</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>int</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>mes</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>color</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>end</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>do</string>
			<key>name</key>
			<string>keyword.hsp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hsp</string>
	<key>uuid</key>
	<string>d3d12dd3-1899-4392-89e0-155455829488</string>
</dict>
</plist>
